name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # List files because it's good for debugging if needed
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Check out the repository code
      - name: Check out repository code
        uses: actions/checkout@v3

      # Set up Java 17 for runner environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the project and run tests using Maven
      #- name: Build and run tests
      #  run: mvn clean install
